#Install SSM & CLoudwatch, But You have to add Content in SSM Parameter and 

---
- name: Install and Configure Amazon SSM Agent with IAM Role Update
  hosts: my_servers
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Remove amazon-ssm-agent snap (if installed)
      command: sudo snap remove amazon-ssm-agent
      ignore_errors: yes  # Ignore errors if the snap is not installed

    - name: Install required dependencies
      apt:
        name:
          - wget
          - unzip
          - zip
        state: present

    - name: Create /tmp/ssm directory
      file:
        path: /tmp/ssm
        state: directory

    - name: Change directory to /tmp/ssm
      shell: cd /tmp/ssm

    - name: Download Amazon SSM Agent Debian package
      get_url:
        url: "https://s3.amazonaws.com/amazon-ssm-us-east-1/latest/debian_amd64/amazon-ssm-agent.deb"
        dest: /tmp/ssm/amazon-ssm-agent.deb

    - name: Install Amazon SSM Agent using dpkg
      apt:
        deb: /tmp/ssm/amazon-ssm-agent.deb
        state: present

    - name: Start Amazon SSM Agent service
      systemd:
        name: amazon-ssm-agent
        state: started
        enabled: yes

    - name: Download Amazon CloudWatch Agent
      get_url:
        url: https://s3.amazonaws.com/amazoncloudwatch-agent/linux/amd64/latest/AmazonCloudWatchAgent.zip
        dest: /tmp/AmazonCloudWatchAgent.zip

    - name: Unzip Amazon CloudWatch Agent
      unarchive:
        src: /tmp/AmazonCloudWatchAgent.zip
        dest: /tmp/
        remote_src: yes

    - name: Install Amazon CloudWatch Agent
      command: sudo ./install.sh
      args:
        chdir: /tmp/

    - name: Fetch and apply CloudWatch agent configuration from SSM Parameter Store
      command: >
        sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl
        -a fetch-config -m ec2 -c ssm:/alarm/AWS-CWAgentLinConfig -s

    - name: Verify the CloudWatch Agent installation
      command: >
        sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl
        -m ec2 -a status
